# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to any branch. 
# For real use you might want to restrict this to the "prod" branch.
#

name: Run Tests on Push

on:
  push:
    branches: [ "main" ]

jobs:
  test-example-4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (example-4)
        working-directory: ./example-4
        run: npm ci

      - name: Run tests (example-4)
        working-directory: ./example-4
        run: npm test
